# Selecting & Filtering Data

In [1]:
import pandas as pd

#### Create a Sample Dataset

In [2]:
students = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Aishu", "Rahul", "Priya", "John", "Meena", "David"],
    "Age": [22, 23, 21, 24, 22, 23],
    "Department": ["AI", "ML", "DS", "AI", "ML", "DS"],
    "Marks": [95, 88, 91, 84, 89, 76]
})

print(students)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89
5  106  David   23         DS     76

### 1. loc

loc selects data using row labels (index) and column names.

Syntax:

df.loc[row_label, column_name]

Example:

A school administrator wants to view only the student names and marks from the student database.

#### AI/ML Usage

Used to select required features before model training.

Select a Row

In [3]:
students.loc[2]

ID              103
Name          Priya
Age              21
Department       DS
Marks            91
Name: 2, dtype: object

Select Specific Columns

In [4]:
students.loc[:, ["Name", "Marks"]]

    Name  Marks
0  Aishu     95
1  Rahul     88
2  Priya     91
3   John     84
4  Meena     89
5  David     76

### 2. iloc

iloc selects data using integer positions instead of labels.

Syntax:

df.iloc[row_position, column_position]

Example:

An HR manager wants to view the first three employees and selected columns from an employee dataset.

#### AI/ML Usage

Useful when column positions are known instead of column names.

In [5]:
students.iloc[0]

ID              101
Name          Aishu
Age              22
Department       AI
Marks            95
Name: 0, dtype: object

In [6]:
students.iloc[0:3, 1:4]

    Name  Age Department
0  Aishu   22         AI
1  Rahul   23         ML
2  Priya   21         DS

### Difference Between loc and iloc
loc	:

* Uses labels
* Includes end label
* Uses column names
  
iloc:

* Uses integer positions
* Excludes end position like Python slicing
* Uses column numbers

### 3. Boolean Indexing

Boolean Indexing filters rows based on a condition that returns True or False.

Example:

A company wants to find employees earning more than ₹50,000.

#### AI/ML Usage

Used to remove unwanted records before training.

In [7]:
students["Marks"] > 90

0     True
1    False
2     True
3    False
4    False
5    False
Name: Marks, dtype: bool

Using it to filter:

In [8]:
students[students["Marks"] > 90]

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
2  103  Priya   21         DS     91

### 4. Filtering Rows

Filtering returns only the rows that satisfy a given condition.

Example:

A bank filters customers who have:

* Account balance above ₹1,00,000
* Premium membership

#### AI/ML Usage

Filtering removes unnecessary data before feature engineering.

Students with Marks greater than or equal to 90.

In [10]:
students[students["Marks"] >= 90]

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
2  103  Priya   21         DS     91

Students from AI Department.

In [12]:
students[students["Department"] == "AI"]

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
3  104   John   24         AI     84

Multiple Conditions

In [13]:
students[
    (students["Department"] == "ML") &
    (students["Marks"] > 85)
]

    ID   Name  Age Department  Marks
1  102  Rahul   23         ML     88
4  105  Meena   22         ML     89

### 5. query()

query() filters rows using SQL-like expressions.

It makes filtering easier to read.

Syntax:

df.query("condition")

Example:

A manager searches for employees with more than five years of experience and a salary above ₹60,000.

#### AI/ML Usage

Makes complex filtering conditions easier to write and understand.

In [14]:
students.query("Marks > 90")

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
2  103  Priya   21         DS     91

In [15]:
students.query("Department == 'AI'")

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
3  104   John   24         AI     84

In [16]:
students.query("Age >= 22 and Marks >= 85")

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
4  105  Meena   22         ML     89

### 6. isin()

isin() checks whether each value exists in a given list.

Syntax:

df["column"].isin(list)

Example:

A company wants to view employees working only in the IT and Finance departments.

#### AI/ML Usage

Useful when filtering multiple categories.

In [17]:
students[
    students["Department"].isin(["AI", "DS"])
]

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
2  103  Priya   21         DS     91
3  104   John   24         AI     84
5  106  David   23         DS     76

### 7. between()

between() checks whether values fall within a specified range.

Syntax:

df["column"].between(start, end)

Example:

A teacher wants to identify students whose marks are between 85 and 92.

#### AI/ML Usage

Used to select records within acceptable ranges, such as age, salary, or income.

In [18]:
students[
    students["Marks"].between(85, 92)
]

    ID   Name  Age Department  Marks
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
4  105  Meena   22         ML     89

### 8. Sorting Data

Sorting arranges data in ascending or descending order.

Example:

An online shopping website sorts products by price, rating, or popularity.

#### AI/ML Usage

Sorting helps identify top-performing records, detect anomalies, and rank prediction results.

Sort by Marks

In [19]:
students.sort_values("Marks")

    ID   Name  Age Department  Marks
5  106  David   23         DS     76
3  104   John   24         AI     84
1  102  Rahul   23         ML     88
4  105  Meena   22         ML     89
2  103  Priya   21         DS     91
0  101  Aishu   22         AI     95

Sort in Descending Order

In [20]:
students.sort_values(
    "Marks",
    ascending=False
)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
2  103  Priya   21         DS     91
4  105  Meena   22         ML     89
1  102  Rahul   23         ML     88
3  104   John   24         AI     84
5  106  David   23         DS     76

Sort by Multiple Columns

In [21]:
students.sort_values(
    ["Department", "Marks"],
    ascending=[True, False]
)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
3  104   John   24         AI     84
2  103  Priya   21         DS     91
5  106  David   23         DS     76
4  105  Meena   22         ML     89
1  102  Rahul   23         ML     88