# Reading & Writing Data

In [1]:
import pandas as pd
import numpy as np

In [2]:
students = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Aishu", "Rahul", "Priya", "John", "Meena"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["AI", "ML", "DS", "AI", "ML"],
    "Marks": [95, 88, 91, 84, 89]
})

print(students)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

### 1. CSV Files

CSV (Comma Separated Values) stores tabular data where each value is separated by commas.

It is the most commonly used format in Data Science and Machine Learning.

Example:

An e-commerce company exports its daily sales report as a CSV file.

#### Write CSV

In [3]:
students.to_csv("students.csv", index=False)

print("CSV file created successfully.")

CSV file created successfully.

#### Read CSV

In [4]:
df = pd.read_csv("students.csv")

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### AI/ML Usage

Most datasets downloaded from Kaggle are stored as CSV files.

### 2. Excel Files

Excel files store data in worksheets with the extensions .xlsx or .xls.

Example:

A company's HR department stores employee records in Excel files.

#### Write Excel

In [5]:
students.to_excel("students.xlsx", index=False)

print("Excel file created successfully.")

Excel file created successfully.

#### Read Excel

In [6]:
df = pd.read_excel("students.xlsx")

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### AI/ML Usage

Business datasets are often received in Excel format before being cleaned and converted for machine learning.

### 3. JSON Files
JSON (JavaScript Object Notation) stores data as key-value pairs.

It is widely used in APIs and web applications.

Example:

A weather API returns temperature, humidity, and wind speed in JSON format.

#### Write JSON

In [7]:
students.to_json(
    "students.json",
    orient="records",
    indent=4
)

print("JSON file created.")

JSON file created.

#### Read JSON

In [8]:
df = pd.read_json("students.json")

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### AI/ML Usage

Many REST APIs return JSON data, which is loaded into Pandas for analysis.

### 4. Parquet Files
Parquet is a column-based storage format that is highly compressed and optimized for big data processing.

Example:

Netflix stores large user-viewing datasets in Parquet because it loads faster and uses less storage.

#### Write Parquet

In [9]:
!pip install pyarrow

Requirement already satisfied: pyarrow in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (25.0.0)

In [10]:
!python -m pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.2.1)

WARNING: Cache entry deserialization failed, entry ignored
WARNING: Cache entry deserialization failed, entry ignored

In [11]:
!pip install fastparquet

Requirement already satisfied: fastparquet in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (2026.5.0)
Requirement already satisfied: pandas>=1.5.0 in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastparquet) (3.0.4)
Requirement already satisfied: numpy in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastparquet) (2.5.0)
Requirement already satisfied: cramjam>=2.3 in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastparquet) (2026.7.0)
Requirement already satisfied: packaging in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from fastparquet) (26.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.5.0->fastparquet) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\nithy\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)

In [12]:
students.to_parquet(
    "students.parquet",
    engine="fastparquet",
    index=False
)

print("Parquet file created.")

Parquet file created.

#### Read Parquet

In [13]:
df = pd.read_parquet("students.parquet",engine="fastparquet")

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### AI/ML Usage

Large datasets in Spark and cloud platforms are commonly stored in Parquet format.

### 5. Pickle Files
Pickle stores Python objects in a binary format.

Unlike CSV or Excel, Pickle preserves the original Python object.

Example:

A data scientist saves a cleaned DataFrame to avoid repeating preprocessing every time.

#### Write Pickle

In [14]:
students.to_pickle("students.pkl")

print("Pickle file created.")

Pickle file created.

#### Read Pickle

In [15]:
df = pd.read_pickle("students.pkl")

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### AI/ML Usage

Pickle is commonly used to save processed datasets and trained machine learning models.

### 6. SQL Tables
SQL databases store data in tables consisting of rows and columns.

Pandas can both read from and write to SQL databases.

Example:

Banks store customer transactions in SQL databases.

In [16]:
import sqlite3

#### Create Database Connection

In [17]:
connection = sqlite3.connect("students.db")

#### Write DataFrame to SQL Table

In [18]:
students.to_sql(
    "student_table",
    connection,
    if_exists="replace",
    index=False
)

print("Table created successfully.")

Table created successfully.

#### Read SQL Table

In [19]:
df = pd.read_sql(
    "SELECT * FROM student_table",
    connection
)

print(df)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### Close Connection

In [ ]:
connection.close()

#### AI/ML Usage

Machine learning projects often retrieve customer, sales, or medical data directly from SQL databases.

### 7. Reading Multiple Files

Sometimes data is split across multiple files, and we need to combine them into one DataFrame.

Example:

A supermarket stores one sales CSV file for each month.

January.csv

February.csv

March.csv

The analyst combines them into one dataset.

#### Create Two Sample Files

In [22]:
sales1 = pd.DataFrame({
    "Product": ["Laptop", "Phone"],
    "Sales": [100, 200]
})

sales2 = pd.DataFrame({
    "Product": ["Tablet", "Watch"],
    "Sales": [150, 120]
})

sales1.to_csv("sales1.csv", index=False)
sales2.to_csv("sales2.csv", index=False)

print(sales1)
print()
print(sales2)

  Product  Sales
0  Laptop    100
1   Phone    200

  Product  Sales
0  Tablet    150
1   Watch    120

### Read Multiple Files

In [21]:
df1 = pd.read_csv("sales1.csv")

df2 = pd.read_csv("sales2.csv")

combined = pd.concat([df1, df2], ignore_index=True)

print(combined)

  Product  Sales
0  Laptop    100
1   Phone    200
2  Tablet    150
3   Watch    120

#### AI/ML Usage

Many datasets are split into multiple files due to their size. They are merged before training a model.

### 8. File Path Handling
A file path specifies the location of a file on the computer.

There are two types:

* Relative Path
* Absolute Path

#### Relative Path

Uses the current working directory.

In [23]:
df = pd.read_csv("students.csv")
df

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### Absolute Path
Specifies the complete location.

In [24]:
df = pd.read_csv(
    r"C:\Users\nithy\OneDrive\Desktop\Stackly\Sprint_3\students.csv"
)
df

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

#### Finding the Current Working Directory

In [25]:
import os

print(os.getcwd())

C:\Users\nithy\OneDrive\Desktop\Stackly\Sprint_3

Example:

A company stores datasets in different folders

#### AI/ML Usage
Correct file path handling ensures notebooks and scripts can locate datasets, making projects portable across different systems and collaborators.