# Data Inspection

In [2]:
import pandas as pd

#### Create a Sample Dataset

In [3]:
students = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105],
    "Name": ["Aishu", "Rahul", "Priya", "John", "Meena"],
    "Age": [22, 23, 21, 24, 22],
    "Department": ["AI", "ML", "DS", "AI", "ML"],
    "Marks": [95, 88, 91, 84, 89]
})

print(students)

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

### 1. head()

head() displays the first five rows of a DataFrame by default.

It is useful for quickly checking whether the dataset has been loaded correctly.

Syntax:

df.head()

We can also specify the number of rows.

df.head(n)

Example:

A data analyst loads a CSV file containing 1 million customer records. Instead of displaying the entire dataset, they use head() to verify that the data has been imported correctly.

#### AI/ML Usage

Used to quickly inspect datasets before preprocessing and model training.

In [4]:
students.head()

    ID   Name  Age Department  Marks
0  101  Aishu   22         AI     95
1  102  Rahul   23         ML     88
2  103  Priya   21         DS     91
3  104   John   24         AI     84
4  105  Meena   22         ML     89

### 2. tail()

tail() displays the last five rows of a DataFrame.

Example:

A company checks the latest customer transactions by viewing the last few rows of a daily sales dataset.

#### AI/ML Usage

Useful for verifying recently appended records in large datasets.

In [6]:
students.tail(2)

    ID   Name  Age Department  Marks
3  104   John   24         AI     84
4  105  Meena   22         ML     89

### 3. sample()

sample() returns randomly selected rows from a DataFrame.

Syntax:

df.sample(n)

Example:

A teacher randomly selects two students for an oral presentation.

#### AI/ML Usage

Used for random data inspection, testing, and creating sample datasets.

In [7]:
students.sample(2)

    ID   Name  Age Department  Marks
1  102  Rahul   23         ML     88
4  105  Meena   22         ML     89

### 4. info()

info() provides a summary of the DataFrame.

It displays:

* Number of rows
* Number of columns
* Column names
* Data types
* Missing values
* Memory usage

Example:

Before cleaning employee records, an HR analyst checks which columns have missing values and their data types.

#### AI/ML Usage

Used to understand the dataset before feature engineering and preprocessing.

In [8]:
students.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          5 non-null      int64
 1   Name        5 non-null      str
 2   Age         5 non-null      int64
 3   Department  5 non-null      str
 4   Marks       5 non-null      int64
dtypes: int64(3), str(2)
memory usage: 366.0 bytes

### 5. describe()

describe() generates statistical summaries of numerical columns.

It provides:

* Count
* Mean
* Standard deviation
* Minimum
* Maximum
* Quartiles
  
Example:

A hospital calculates the average age and maximum age of patients.

#### AI/ML Usage

Used to identify outliers and understand feature distributions.

In [9]:
students.describe()

               ID        Age      Marks
count    5.000000   5.000000   5.000000
mean   103.000000  22.400000  89.400000
std      1.581139   1.140175   4.037326
min    101.000000  21.000000  84.000000
25%    102.000000  22.000000  88.000000
50%    103.000000  22.000000  89.000000
75%    104.000000  23.000000  91.000000
max    105.000000  24.000000  95.000000

### 6. shape

shape returns the number of rows and columns.

Example:

A company checks whether the downloaded sales dataset contains the expected number of records.

#### AI/ML Usage

Used to verify dataset size before model training.

In [10]:
students.shape

(5, 5)

Meaning:

5 rows

5 columns

### 7. columns

columns returns the names of all columns.

Example:

An analyst checks available columns before selecting features for analysis.

#### AI/ML Usage

Used for feature selection and column renaming.

In [11]:
students.columns

Index(['ID', 'Name', 'Age', 'Department', 'Marks'], dtype='str')

### 8. dtypes

dtypes displays the data type of every column.

Example:

A bank verifies whether transaction amounts are stored as numbers instead of text.

#### AI/ML Usage

Correct data types are required before applying machine learning algorithms.

In [12]:
students.dtypes

ID            int64
Name            str
Age           int64
Department      str
Marks         int64
dtype: object

### 9. memory_usage()

memory_usage() shows how much memory each column occupies.

Example:

A company working with millions of records checks memory usage to optimize storage and improve performance.

#### AI/ML Usage

Used to reduce memory consumption in large datasets.

In [13]:
students.memory_usage()

Index         132
ID             40
Name           64
Age            40
Department     50
Marks          40
dtype: int64

### 10. nunique()

nunique() returns the number of unique values in each column.

Example:

A supermarket checks how many different product categories are available.

#### AI/ML Usage

Helps identify categorical features and low-cardinality columns.

In [14]:
students.nunique()

ID            5
Name          5
Age           4
Department    3
Marks         5
dtype: int64

### 11. value_counts()

value_counts() counts how many times each unique value appears in a column.

Example:

An HR department counts how many employees belong to each department.

#### AI/ML Usage

Useful for checking class balance in classification problems.

In [15]:
students["Department"].value_counts()

Department
AI    2
ML    2
DS    1
Name: count, dtype: int64